/* 
 * File:   main.h
 * Author: Table8-2
 *
 * Created on 24 septembre 2024, 15:57
 */

#ifndef MAIN_H
#define	MAIN_H
#define STATE_NULL 18
#define STATE_ATTENTE 0
#define STATE_ATTENTE_EN_COURS 1
#define STATE_AVANCE 2
#define STATE_AVANCE_EN_COURS 3
#define STATE_TOURNE_GAUCHE 4
#define STATE_TOURNE_GAUCHE_EN_COURS 5
#define STATE_TOURNE_DROITE 6
#define STATE_TOURNE_DROITE_EN_COURS 7
#define STATE_TOURNE_SUR_PLACE_GAUCHE 8
#define STATE_TOURNE_SUR_PLACE_GAUCHE_EN_COURS 9
#define STATE_TOURNE_SUR_PLACE_DROITE 10
#define STATE_TOURNE_SUR_PLACE_DROITE_EN_COURS 11
#define STATE_ARRET 12
#define STATE_ARRET_EN_COURS 13
#define STATE_RECULE 14
#define STATE_RECULE_EN_COURS 15
#define STATE_RALENTI 16
#define STATE_RALENTI_EN_COURS 17
#define STATE_AVANCE_DOUCEMENT 19
#define STATE_AVANCE_DOUCEMENT_EN_COURS 20
#define STATE_AVANCE2 21
#define STATE_AVANCE_EN_COURS2 22
#define OBSTACLE_EXD 23
#define OBSTACLE_EXG 26
#define STATE_GAUCHE2 24
#define STATE_GAUCHE2_EN_COURS 27
#define STATE_DROITE2 25
#define STATE_DROITE2_EN_COURS 28
#define PAS_D_OBSTACLE 0
#define OBSTACLE_A_GAUCHE 1
#define OBSTACLE_A_DROITE 2
#define OBSTACLE_EN_FACE 3
#define OBSTACLE_PARTOUT 4
#define OBSTACLE_EXTREME_GAUCHE 5
#define OBSTACLE_EXTREME_DROITE 6
#define OBSTACLE_DEVANT 7
#define OBSTACLE_EX 8
#define OBSTACLE_EX_DROITE_CENTRE 9
#define OBSTACLE_EX_GAUCHE_CENTRE 10
#define OBSTACLE_EN_FACE2 11
#define OBSTACLE_DROITE_ET_EX 12
#define OBSTACLE_GAUCHE_ET_EX 13
#define OBSTACLE_EX_GAUCHE_GAUCHE_ET_EX_DROITE_DROITE 14
#include "ChipConfig.h"
extern unsigned long timestamp;
void lumierecapteur();
void OperatingSystemLoop(void);
void SetNextRobotStateInAutomaticMode();




#endif	/* MAIN_H */

